export { default as AuthTemplate } from './AuthTemplate/AuthTemplate'
export { default as ChannelTemplate } from './ChannelTemplate/ChannelTemplate'
export { default as CreateChannelTemplate } from './CreateChannelTemplate/CreateChannelTemplate'
export { default as HomeTemplate } from './HomeTemplate/HomeTemplate'
export { default as NotFoundTemplate } from './NotFoundTemplate/NotFoundTemplate'
export { default as UserChannelsTemplate } from './UserChannelsTemplate/UserChannelsTemplate'
export { default as UserProfileTemplate } from './UserProfileTemplate/UserProfileTemplate'
export { default as UserRegistrationTemplate } from './UserRegistrationTemplate/UserRegistrationTemplate'

export { default as Layout } from '../Layout/Layout'
